const VERSION="1.3";
const ENDPOINT="https://eopvkwhcgznvubesaszv.supabase.co/functions/v1/zahnkultur-ai";
const panel=document.querySelector(".chat-app"),messages=document.querySelector("#chatMessages"),form=document.querySelector("#chat"),input=document.querySelector("#input");
let messageCount=Number(sessionStorage.getItem("zahnkultur_ai_message_count")||"0"),adminToken="",conversation=[];
function add(text,cls){const el=document.createElement("div");el.className="msg "+cls;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}
function status(t){document.querySelector("#status").textContent=t}
function clean(t){return String(t||"").replace(/^\s*Hallo!\s*Ich bin dein persönlicher Zahnkultur-Assistent\.\s*/i,"").replace(/[\*#_`~]/g,"").replace(/^\s*>\s?/gm,"").replace(/^\s*(?:[-+•]|\d+[.)])\s+/gm,"").replace(/\[([^\]]+)\]\([^)]*\)/g,"$1").replace(/\n{3,}/g,"\n\n").trim()}
async function api(body){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Serverfehler");return d}
function newChat(){messages.innerHTML="";messageCount=0;conversation=[];sessionStorage.removeItem("zahnkultur_ai_message_count");add("Hallo! Ich bin dein persönlicher Zahnkultur-Assistent.\n\nWie kann ich Ihnen helfen?","ai");input.focus()}
newChat();
document.querySelector("#menuBtn").onclick=()=>{document.querySelector("#drawer").classList.add("open");document.querySelector("#drawerBackdrop").classList.add("open")};
function closeMenu(){document.querySelector("#drawer").classList.remove("open");document.querySelector("#drawerBackdrop").classList.remove("open")}
document.querySelector("#closeMenu").onclick=closeMenu;document.querySelector("#drawerBackdrop").onclick=closeMenu;
document.querySelector("#newChat").onclick=()=>{closeMenu();newChat()};
async function ping(){status("Ping …");try{const d=await api({mode:"ping"});status(d.aiConfigured?"Backend + KI bereit":"Backend bereit · KI nicht konfiguriert");add("PONG — Backend erreichbar.\nKI-Konfiguration: "+(d.aiConfigured?"bereit":"nicht eingerichtet")+".\nKein KI-Aufruf wurde für den Ping gemacht.","ai")}catch(e){status("Backend nicht erreichbar");add("PING FEHLGESCHLAGEN — Backend nicht erreichbar.","ai")}}
async function aiTest(){status("AI-Test …");try{const d=await api({mode:"ai-test"});status(d.aiResponded?"AI antwortet":"AI nicht verfügbar");add("AI-TEST "+(d.aiResponded?"OK":"NICHT VERFÜGBAR")+"\n\n"+(d.reply||"Keine Antwort erhalten."),"ai")}catch(e){status("AI-Test fehlgeschlagen");add("AI-TEST FEHLGESCHLAGEN — "+e.message,"ai")}}
document.querySelector("#pingBtn").onclick=ping;document.querySelector("#pingBtnMenu").onclick=()=>{closeMenu();ping()};document.querySelector("#aiTestBtn").onclick=aiTest;document.querySelector("#aiTestBtnMenu").onclick=()=>{closeMenu();aiTest()};
function updateApp(){location.replace(location.pathname+"?v="+VERSION+"&cache="+Date.now())}document.querySelector("#updateApp").onclick=updateApp;document.querySelector("#updateAppMenu").onclick=()=>{closeMenu();updateApp()};
document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{input.value=b.dataset.q;form.requestSubmit()});
form.onsubmit=async e=>{e.preventDefault();e.stopPropagation();const message=input.value.trim();if(!message)return;input.value="";if(message.toLowerCase()==="/exit"){adminToken="";status("Bereit");add("Admin-Modus beendet.","ai");return}if(message.toLowerCase()==="ping"){ping();return}const first=messageCount===0;messageCount++;sessionStorage.setItem("zahnkultur_ai_message_count",String(messageCount));add(message,"user");const pending=add("…","ai");try{const d=await api({message,isFirstMessage:first,adminToken,conversation});if(d.adminToken){adminToken=d.adminToken;pending.textContent=d.reply||"Admin-Modus aktiviert.";status("Admin-Modus")}else{pending.textContent=clean(d.reply)||"Keine Antwort erhalten.";conversation.push({role:"user",content:message},{role:"assistant",content:pending.textContent});status("Bereit")}}catch(err){pending.textContent="Die Anfrage konnte gerade nicht verarbeitet werden. Bitte versuchen Sie es erneut.";status("Bereit")}input.focus()};
