const VERSION="1.1";
const ENDPOINT="https://eopvkwhcgznvubesaszv.supabase.co/functions/v1/zahnkultur-ai";
const chatPanel=document.querySelector("#chatPanel"),chatMessages=document.querySelector("#chatMessages"),form=document.querySelector("#chat"),input=document.querySelector("#input");
let messageCount=Number(sessionStorage.getItem("zahnkultur_ai_message_count")||"0"),adminToken="",adminMode=false;const conversation=[];
function add(text,cls){const el=document.createElement("div");el.className="msg "+cls;el.textContent=text;chatMessages.appendChild(el);chatMessages.scrollTop=chatMessages.scrollHeight;return el}
function setStatus(t){const s=document.querySelector("#status");if(s)s.textContent=t}
function clean(t){return String(t||"").replace(/^\s*Hallo!\s*Ich bin dein persönlicher Zahnkultur-Assistent\.\s*/i,"").trim()}
function openChat(){chatPanel.classList.add("open");chatPanel.setAttribute("aria-hidden","false");input.focus();if(!chatMessages.children.length)add("Hallo! Ich bin dein persönlicher Zahnkultur-Assistent.\n\nIch kann Ihnen Informationen zur Praxis, zu Leistungen, Technik, Sprechzeiten und zur Terminvereinbarung geben.","ai")}
function closeChat(){chatPanel.classList.remove("open");chatPanel.setAttribute("aria-hidden","true")}
function menu(open){document.querySelector("#drawer").classList.toggle("open",open);document.querySelector("#drawerBackdrop").classList.toggle("open",open)}
document.querySelector("#menuBtn").onclick=()=>menu(true);document.querySelector("#closeMenu").onclick=()=>menu(false);document.querySelector("#drawerBackdrop").onclick=()=>menu(false);
document.querySelector("#openChatFromMenu").onclick=()=>{menu(false);openChat()};document.querySelector("#chatFab").onclick=openChat;document.querySelector("#closeChat").onclick=closeChat;
document.querySelector("#heroChat").onclick=()=>document.querySelector("#reasons").scrollIntoView({behavior:"smooth"});document.querySelector("#infoChat").onclick=openChat;
document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{openChat();input.value=b.dataset.q;form.requestSubmit()});
async function callApi(body){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Serverfehler");return d}
document.querySelector("#pingBtn").onclick=async()=>{setStatus("Ping …");try{const d=await callApi({mode:"ping"});setStatus(d.aiConfigured?"Backend + KI bereit":"Backend bereit · KI nicht konfiguriert");add("PONG — Backend erreichbar.\nKI-Konfiguration: "+(d.aiConfigured?"bereit":"nicht eingerichtet")+".\nKein KI-Aufruf wurde für den Ping gemacht.","ai")}catch(e){setStatus("Backend nicht erreichbar");add("PING FEHLGESCHLAGEN — Der Supabase-Endpunkt ist nicht erreichbar.","ai")}};
document.querySelector("#aiTestBtn").onclick=async()=>{setStatus("AI-Test …");try{const d=await callApi({mode:"ai-test"});if(d.aiResponded){setStatus("AI antwortet");add("AI-TEST OK — Die KI hat auf den Funktionstest geantwortet.\n\nAntwort: "+d.reply,"ai")}else{setStatus("AI nicht verfügbar");add("AI-TEST: "+(d.reply||"Die KI ist nicht konfiguriert."),"ai")}}catch(e){setStatus("AI-Test fehlgeschlagen");add("AI-TEST FEHLGESCHLAGEN — "+e.message,"ai")}};
document.querySelector("#updateApp").onclick=()=>{sessionStorage.removeItem("zahnkultur_ai_message_count");location.replace(location.origin+location.pathname+"?cache="+Date.now())};
async function ask(message,first){return callApi({message,isFirstMessage:first,adminToken,conversation})}
form.onsubmit=async e=>{e.preventDefault();e.stopPropagation();const message=input.value.trim();if(!message)return;input.value="";add(message,"user");if(message.toLowerCase()==="/exit"){adminToken="";adminMode=false;setStatus("Bereit");add("Admin-Modus beendet.","ai");return}if(message.toLowerCase()==="ping"){document.querySelector("#pingBtn").click();return}const first=messageCount===0;messageCount++;sessionStorage.setItem("zahnkultur_ai_message_count",String(messageCount));const pending=add("…","ai");try{const d=await ask(message,first);if(d.adminToken){adminToken=d.adminToken;adminMode=true;pending.textContent=d.reply||"Admin-Modus aktiviert.";setStatus("Admin-Modus")}else{pending.textContent=first?clean(d.reply):d.reply||"Keine Antwort erhalten.";conversation.push({role:"user",content:message},{role:"assistant",content:pending.textContent})}}catch(err){console.error(err);pending.textContent="Die Anfrage konnte gerade nicht verarbeitet werden. Bitte versuchen Sie es erneut oder kontaktieren Sie die Praxis direkt.";setStatus("Bereit")};input.focus()};